//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParatechnikaJellemzok {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParatechnikaJellemzok.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott érték csak {0} és {1} közötti egész szám lehet..
        /// </summary>
        internal static string CsakMinEsMaxKoztiErtekLehet {
            get {
                return ResourceManager.GetString("CsakMinEsMaxKoztiErtekLehet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg {0} értékét (pozitív szám):.
        /// </summary>
        internal static string ErtekBekeres {
            get {
                return ResourceManager.GetString("ErtekBekeres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás érték. Csak pozitív szám adható meg. A program leáll..
        /// </summary>
        internal static string HibasErtekCsakPozitiv {
            get {
                return ResourceManager.GetString("HibasErtekCsakPozitiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás választás. A program leáll..
        /// </summary>
        internal static string HibasValasztas {
            get {
                return ResourceManager.GetString("HibasValasztas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Légréteget szeretne számolni? (i/n).
        /// </summary>
        internal static string LegretegetVagyNem {
            get {
                return ResourceManager.GetString("LegretegetVagyNem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg a légréteg átlaghőmérsékletét (°C, pozitív szám):.
        /// </summary>
        internal static string LegretegHomersekletBekeres {
            get {
                return ResourceManager.GetString("LegretegHomersekletBekeres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott érték nem lehet üres..
        /// </summary>
        internal static string NemLehetUres {
            get {
                return ResourceManager.GetString("NemLehetUres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melyik páratechnikai jellemzőt szeretné megadni? (1: Páradiffúziós egyenértékű légrétegvastagság (Sd), 2: Páradiffúziós ellenállási szám (μ), 3: Páradiffúziós tényező (δ).
        /// </summary>
        internal static string ParatechnikaiJellemzoValasztas {
            get {
                return ResourceManager.GetString("ParatechnikaiJellemzoValasztas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg a réteg vastagságát cm-ben (pozitív szám):.
        /// </summary>
        internal static string RetegVastagsagBekeres {
            get {
                return ResourceManager.GetString("RetegVastagsagBekeres", resourceCulture);
            }
        }
    }
}
